import sqlite3
import os

class AIStrategist:
    def __init__(self):
        # التأكد من وجود مجلد الخزنة لحفظ الخبرات [2026-01-11]
        if not os.path.exists('vault'):
            os.makedirs('vault')
            
        # إنشاء قاعدة بيانات الخبرات التراكمية
        self.conn = sqlite3.connect('vault/experience.db')
        self.cursor = self.conn.cursor()
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS knowledge 
                               (genre TEXT, pattern TEXT, quality_score REAL)''')
        self.conn.commit()

    def analyze_genre(self, user_description):
        # منطق الوعي: تحليل الكلمات المفتاحية لتحديد نوع اللعبة وهويتها
        desc = user_description.lower()
        if any(word in desc for word in ["حرب", "قتال", "شوتر", "pubg"]):
            return "WAR_GENRE"
        elif any(word in desc for word in ["سيارات", "سباق", "تفحيط", "car"]):
            return "RACING_GENRE"
        return "UNKNOWN_MEGA_PROJECT"

    def generate_game_logic(self, genre_analysis):
        # بناء هيكل اللعبة (التوليد التلقائي) بناءً على التحليل الاستراتيجي
        if genre_analysis == "WAR_GENRE":
            return """
# War Engine Generated by Sovereign Titan Core
class WarGame:
    def __init__(self):
        self.gravity = 9.8
        self.bullet_speed = 900 
        self.ai_difficulty = "Dynamic"
        print("Sovereign Intelligence: War System Deployed.")
            """
        elif genre_analysis == "RACING_GENRE":
            return """
# Racing Engine Generated by Sovereign Titan Core
class RacingGame:
    def __init__(self):
        self.friction = 0.5
        self.max_speed = 320 
        self.drift_physics = True
        print("Sovereign Intelligence: Racing System Deployed.")
            """
        return "# Standard Framework Initialized."

    def save_and_learn(self, genre, code):
        # حفظ الملف المولد
        with open("generated_game.py", "w", encoding='utf-8') as f:
            f.write(code)
        
        # حفظ الخبرة في الخزنة ليتعلم المصنع ذاتياً
        self.cursor.execute("INSERT INTO knowledge VALUES (?, ?, ?)", (genre, "Generation_Success", 1.0))
        self.conn.commit()
        return "تم توليد اللعبة بنجاح وحفظ التجربة في الخزنة الملكية."

# وحدة التنسيق (التي سيستخدمها ملف main.py)
def factory_pipeline(description):
    brain = AIStrategist()
    genre = brain.analyze_genre(description)
    code = brain.generate_game_logic(genre)
    result = brain.save_and_learn(genre, code)
    return result
