name: Sovereign_Titan_Final_Green
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create Structure
        run: mkdir -p concepts games vault core/config utils core/cognitive_engine
      - name: Install Essential Deps
        run: pip install requests beautifulsoup4 pyyaml
      - name: Execute Sovereign Core
        run: python main.py
